### ISSUE TITLE
unity version compatibility  ?

### ISSUE THREAD

**Issue by sancelot** [Unity-Technologies/URDF-Importer#10]
I tried with unity 2019.4.15f1 it failed.

**Comment by Transzendental** [comment]
You'll have to use Unity 2020.2 or newer (which right now is a beta version) See here: [urdf_tutorial](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/urdf_importer/urdf_tutorial.md)

**Comment by mpinol** [comment]
Closing as the correct response to the issue was posted. Please open another issue if you are still experiencing problems after switching to Unity 2020.2 or newer!
