### ISSUE TITLE
Cannot click Import Robot from Selected URDF File 

### ISSUE THREAD

**Issue by madd-aj** [Unity-Technologies/URDF-Importer#113]
![Screenshot 2021-05-30 151152](https://user-images.githubusercontent.com/78703972/120120280-696e0480-c159-11eb-8312-78d9d8083456.png)

I tried right-clicking it as I saw someone else said, but that doesn't work either. Not sure what's going on here.
Using Unity 2020.2.0b93373

Thank you!

**Comment by peifeng-unity** [comment]
Hello @madd-aj, sorry for the late reply. You may need to right-click on the [`niryo_one.urdf`](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/pick_and_place/PickAndPlaceProject/Assets/URDF/niryo_one/niryo_one.urdf) file inside the `niryo_one` folder. Please let us know if this could help to solve your issue.

**Comment by at669** [comment]
Hi all, I will be closing this ticket as the solution has been provided and also due to inactivity. Please feel free to reopen the ticket if the problem persists. Thanks!
