### ISSUE TITLE
Importing URDF

### ISSUE THREAD

**Issue by Coloradete** [Unity-Technologies/URDF-Importer#13]
Hello, I am following the guidelines form the Readme tutorial and it says

[...]
    Copy the URDFLibrary and UnityEditorScripts directories into the newly created Assets/Plugins directory
[...]

But there are no folders named URDFLibrary and UnityEditorScripts in the repository https://github.com/Unity-Technologies/URDF-Importer. I tried copying the whole repository in an empty Unity 2020.2.0b9 project but I get the following error saying the MeshProcess namespace could not be found

Assets/Plugins/URDF-Importer-main/Editor/NeedsRuntimeConversion/Extensions/UrdfGeometryCollision.cs(6,7): error CS0246: The type or namespace name 'MeshProcess' could not be found (are you missing a using directive or an assembly reference?)

Any guidence? 

Thank you!

**Comment by vidurvij-Unity** [comment]
Hi @Coloradete 
Thank you for bringing this to our attention.
I have updated the instructions on the repo. You can follow these instructions to add the URDF Importer from Package Manager and import a robot. 
Please try the updated instructions and feel free to open another issue if you come across any other problem.
Vidur
