### ISSUE TITLE
Missing collision meshes references in generated mesh colliders

### ISSUE THREAD

**Issue by thibnoel** [Unity-Technologies/URDF-Importer#135]
**Describe the bug**
Hello,
I noticed that using the URDF importer with a URDF model containing multiple references to the same collision mesh leads to missing mesh colliders in the generated Unity model for all links sharing this reference except one (specifically, the mesh colliders under ArticulationBody/Collisions/link are generated correctly but without a reference to the correct mesh)

**To Reproduce**
1. Download a URDF with multiple ref. to a same collision mesh (the PR2 for example : https://github.com/PR2/pr2_common/tree/melodic-devel/pr2_description) and the associated meshes
2. Use the URDF Importer as described in the tutorials
3. Check the wheels ArticulationBody in the editor : one clearly displays the mesh collider, not the other
4. On play, one of the wheels goes through the ground

**Console logs / stack traces**
Not applicable

**Expected behavior**
All ArticulationBody generated by the URDF Importer have correctly referenced meshes for their children mesh colliders.

**Screenshots**
Example with a 2 armed robot : 
Left arm with correct reference to the collision meshes : 
![correct_behavior](https://user-images.githubusercontent.com/43820910/126455315-f0eea2b3-592e-4f8d-82fd-d710db7a1ca4.jpg)
Right arm with correct hierarchy generation but unreferenced collision meshes : 
![incorrect_behavior](https://user-images.githubusercontent.com/43820910/126455404-f86aebab-b750-4cfc-8af0-b263bb861b8d.jpg)

**Environment (please complete the following information, where applicable):**
- Unity Version: Unity 2021.2.0b1
- Unity machine OS + version: Ubuntu 20.04
- ROS machine OS + version: Ubuntu 18.04, ROS melodic
- ROS–Unity communication: ROS-TCP endpoint
- Branch or version: v0.5.0

**Additional context**
None

**Comment by LaurieCheers-unity** [comment]
Thanks. I've filed an internal ticket to investigate this issue.

**Comment by at669** [comment]
The PR for this issue has been merged into `dev` and will be in the next release of the URDF-Importer. Please feel free to try it out on `dev`. I'll be closing this issue, but feel free to reopen it if the problem persists, or open a new ticket if you encounter other issues.
