### ISSUE TITLE
Error adding package: https://github.com/Unity-Technologies/URDF-Importer.git?path=/com.unity.robotics.urdf-importer#v0.5.0

### ISSUE THREAD

**Issue by Ro-tico** [Unity-Technologies/URDF-Importer#145]
Hi Unity,

I am following the description in https://github.com/Unity-Technologies/URDF-Importer in order to import a robot in URDF format.  However I get three error in a new project:

![image](https://user-images.githubusercontent.com/89193657/134021745-826fd13a-bed9-4599-a203-7e600c7a1e4e.png)

Could you help me please?

**Comment by sdiao** [comment]
HI @Ro-tico , may I know which version of Unity that you are using? Do you see the same error if you open a new Unity project, and import the URDF package via `https://github.com/Unity-Technologies/URDF-Importer.git?path=/com.unity.robotics.urdf-importer#v0.5.0`?

I was reading on [Unity Forum]( https://forum.unity.com/threads/ebusy-resource-busy-or-locked.845497/) where a similar error "EBUSY: resource busy or locked" is reported. Did you have VS Code open when you ran into the error?  If yes, could you try close VS Code first, and re-import `https://github.com/Unity-Technologies/URDF-Importer.git?path=/com.unity.robotics.urdf-importer#v0.5.0` in Unity Package manager? 

The forum article is: https://forum.unity.com/threads/ebusy-resource-busy-or-locked.845497/

**Comment by at669** [comment]
Hi @Ro-tico, as the answer has been provided in this thread, I will close out this issue. Please feel free to re-open the thread if the issue reoccurs. Thank you!
