### ISSUE TITLE
Imported Robot gameobject not respecting transform modifications via script

### ISSUE THREAD

**Issue by vikas-shah** [Unity-Technologies/URDF-Importer#167]
**Describe the bug**
When a robot is imported using its URDF file, and that robot gameobject is loaded from Unity script it always loads at position 0,0,0 and rotation 0,0,0. Any changes to these never takes effect. However, changes to scale are seen as expected.

**To Reproduce**
1. Checkout the code from my [github repo](https://github.com/vikas-shah/Ur10eTransform)
2. The system version I'm using is:
Unity Hub: 2.4.5
Unity Install: 2020.3.24f1
Ubuntu 20.04
Mono 6.12.0.122
Urdf Importer 0.5.0-preview
3. Run the project in Game mode and verify that the arm prefab is loaded
4. Try changing the transform values for position or rotation - there would be no impact
5. Try changing the scale value and arm dimension will change

**Console logs / stack traces**
No logs / stack traces

**Expected behavior**
The way scale value changes are reflected in prefab, even position / rotation value changes should reflect changes in the scene in game mode

**Screenshots**
None, as the code should show live demo

**Environment (please complete the following information, where applicable):**
- Unity Version: Unity 2020.3.24f1]
- Unity machine OS + version: Ubuntu 20.04
- ROS machine OS + version: ROS is not used / required
- ROS–Unity communication: N/aA
- Branch or version: v0.5.0-preview

**Additional context**
Feel free to raise a PR on github if you reckon I'm doing something wrong.

**Comment by hyounesy** [comment]
URDF importer creates articulation bodies for robot joints and the transformation for articulation bodies is handled by the physics engine, so changing the Transform values in the Unity editor will not have an effect. You can however change the position of the root of the robot using TeleportRoot: https://docs.unity3d.com/2020.1/Documentation/ScriptReference/ArticulationBody.TeleportRoot.html
