### ISSUE TITLE
Non-convex MeshCollider with ArticulationBody is not supported

### ISSUE THREAD

**Issue by agru97** [Unity-Technologies/URDF-Importer#171]
I imported my Robot withe the newest version of the URDF-Importer, but now I have to disable the All Colliders Convex tag in the URDF Robot Script because when the Colliders are enabled my robot behaves very weird.
When they are disabled I get 153 of these errors:
Non-convex MeshCollider with ArticulationBody is not supported.
If you want to use a non-convex mesh either use the Rigidbody kinematic or remove the ArticulationBody component.

**Comment by hyounesy** [comment]
Hi @agru97, thanks for reporting the issue. This is a bit strange, because after importing your robot with URDF-Importer, all the meshes should be decomposed to convex. Have you tried both the `VHACD` and `Unity` for the `Mesh Decomposer` option?

**Comment by hyounesy** [comment]
Created an internal ticket to remove the isConvex flag from URDF Robot as it is only supported by RigidBody's which is not supported anymore: [AIRO-1690]

**Comment by vidurvij-Unity** [comment]
Changes suggested by the issue are merged.
