### ISSUE TITLE
Axis  Orientation Missing

### ISSUE THREAD

**Issue by SwannSchilling** [Unity-Technologies/URDF-Importer#185]
It seems like there is a problem with importing and exporting the joint axis orientation...am I missing something?

**Comment by at669** [comment]
Hi, thanks for the post! I've created an internal ticket to investigate and track this, and the team will get back to you with updates. 

[Ticket#: AIRO-1706]

**Comment by vidurvij-Unity** [comment]
The bug fix has been merged to dev.
