### ISSUE TITLE
An error occurred while adding the URDF package

### ISSUE THREAD

**Issue by slxxqs** [Unity-Technologies/URDF-Importer#19]
When I Add Package from Git URL，there is an error：
Asset Packages/com.unity.robotics.urdf-importer/InfoAcknowledgements.md has no meta file, but it's in an immutable folder. The asset will be ignored.

**Comment by at669** [comment]
Hi @slxxqs, thanks for catching this! I believe this error should not cause issues with development, and we are actively working on a fix for this.

**Comment by at669** [comment]
Hi @slxxqs, this has now been fixed on our `main` branch. You may need to update the package in your local project by re-adding it. I will close out this issue--feel free to open it back up if you continue to encounter problems with this!
