### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by favoyang** [Unity-Technologies/URDF-Importer#27]
tag/v0.0.5
[package.json](https://github.com/Unity-Technologies/URDF-Importer/blob/v0.0.5/package.json): 0.04

To fix: bump package.json version to 0.0.5 and re-tag v0.05.

**Comment by LaurieCheers-unity** [comment]
Thanks, this will be fixed soon.

**Comment by mpinol** [comment]
Closing issue. Package version has been bumped to 1.2.
