### ISSUE TITLE
Wrong joint state from Urdf Joint Revolute

### ISSUE THREAD

**Issue by HenningLuo** [Unity-Technologies/URDF-Importer#40]
HI, 

I have been using Unity Robotics Hub for my own robot. With the `getPosition()` function in for revolute joints, I realised the joint states I got were always close to zero. After checking the code in `UrdfJointRevolute.cs`, I found the following definition.

        public override float GetPosition()
        {
            #if UNITY_2020_1_OR_NEWER
                return ((ArticulationBody)unityJoint).jointPosition[xAxis] * Mathf.Deg2Rad;
            #else
                return -((HingeJoint)unityJoint).angle * Mathf.Deg2Rad;
            #endif
        }

The states are tranformed from degree to radian. Although I am not sure if this is the case for all versions, as least in version 2020.2.0b9, the position from `(ArticulationBody)unityJoint).jointPosition[xAxis]` is already in radian, so they are transformed twice and therefore always close to zero.

It would be greatly appreciated if any members can verify if this is indeed a bug! Thanks in advance.

**Comment by at669** [comment]
Hi @HenningLuo, thanks for catching this! We'll put in a fix for this issue.
