### ISSUE TITLE
import Robot from Selected URDF file cannot be selected

### ISSUE THREAD

**Issue by MrVBian** [Unity-Technologies/URDF-Importer#62]
![image](https://user-images.githubusercontent.com/37790267/110563543-71379180-8186-11eb-8a79-fb47ebaca8b2.png)
![image](https://user-images.githubusercontent.com/37790267/110563598-84e2f800-8186-11eb-9d65-9595521242be.png)

version: Unity2020.2.7f1c1

Thank you very much!

**Comment by vidurvij-Unity** [comment]
Hey @MrVBian,
This is by design. Select the URDF file you want to import in your project view and do right click -> Import Robot from selected URDF File.

**Comment by Axin630** [comment]
> Hey @MrVBian, This is by design. Select the URDF file you want to import in your project view and do right click -> Import Robot from selected URDF File.

Why is ‘Import Robot from selected URDF File’ gray and can't be clicked

**Comment by medhavikamran4** [comment]
What is the answer for this issue? I am facing same problem but it is not clear in the above conversation.  What is the procedure to resolve this issue?

**Comment by hugoyvrn** [comment]
Be careful to click on the urdf file (since `.urdf` is hidden because the file extension may not appear in the Project window.).
