### ISSUE TITLE
[doc]Tutorials page link is outdated

### ISSUE THREAD

**Issue by Kazuchanfl** [Unity-Technologies/URDF-Importer#64]
In README.md, we can find Tutorials page that leads to [here](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/master/tutorials/urdf_importer/urdf_tutorial.md).

But now that **master** branch is no longer present, you are redirected to slightly different page [here](https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/urdf_importer/urdf_tutorial.md).

Message shows,
> Branch not found, redirected to default branch.

**Comment by mrpropellers** [comment]
Hey @Kazuchanfl apologies as we don't have a readily accessible public policy on this, but these changes have already been made on `dev`, which is our active development branch. You should see the changes to the readme reflected in `main` next time we release `dev`.
