### ISSUE TITLE
Cannot Find URDFLibrary and UnityEditorScripts directories 

### ISSUE THREAD

**Issue by ptiwari0664** [Unity-Technologies/URDF-Importer#7]
With Regards to the point 3 : (Copy the URDFLibrary and UnityEditorScripts directories into the newly created Assets/Plugins directory)
- I cannot find these two folders in the git repository. Can anyone please help ?

I copied entire URDF-Importer into Asset/Plugins directory of the project, however In the Asset menu, I cannot find `Import from URDF`

**Comment by Tonirayn** [comment]
you can checkout to commit 1d351d03c07adf7d9c5fbb378d452e8de5d16406

**Comment by ptiwari0664** [comment]
Thanks. This commit works fine.
